import type { User, Listing, Conversation } from './types';

export const users: User[] = [
  { id: 'user-1', name: 'Alice', avatarUrl: 'https://placehold.co/100x100' },
  { id: 'user-2', name: 'Bob', avatarUrl: 'https://placehold.co/100x100' },
  { id: 'user-3', name: 'Charlie', avatarUrl: 'https://placehold.co/100x100' },
];

export const listings: Listing[] = [
  {
    id: 'listing-1',
    title: 'Vintage Leather Sofa',
    description: 'A beautiful vintage sofa, perfect for any living room. Minor wear and tear consistent with age.',
    price: 450,
    category: 'Furniture',
    location: 'San Francisco, CA',
    images: ['https://placehold.co/600x400', 'https://placehold.co/600x400', 'https://placehold.co/600x400'],
    seller: users[0],
    createdAt: '2024-05-20T10:00:00Z',
  },
  {
    id: 'listing-2',
    title: 'Mountain Bike, Like New',
    description: '21-speed mountain bike. Great condition, only ridden a few times. Selling because I\'m moving.',
    price: 250,
    category: 'Bikes',
    location: 'Oakland, CA',
    images: ['https://placehold.co/600x400'],
    seller: users[1],
    createdAt: '2024-05-21T11:30:00Z',
  },
  {
    id: 'listing-3',
    title: 'Acoustic Guitar with Case',
    description: 'Yamaha acoustic guitar. Warm sound. Comes with a hard case and some extra strings.',
    price: 150,
    category: 'Musical Instruments',
    location: 'San Francisco, CA',
    images: ['https://placehold.co/600x400', 'https://placehold.co/600x400'],
    seller: users[0],
    createdAt: '2024-05-19T09:00:00Z',
  },
  {
    id: 'listing-4',
    title: 'Designer Table Lamp',
    description: 'Modernist table lamp. Provides great ambient light. Bulb included.',
    price: 75,
    category: 'Home Decor',
    location: 'Berkeley, CA',
    images: ['https://placehold.co/600x400'],
    seller: users[2],
    createdAt: '2024-05-22T14:00:00Z',
  },
  {
    id: 'listing-5',
    title: 'Set of 4 Dining Chairs',
    description: 'Sturdy wooden dining chairs. Scandinavian design. Some light scratches but otherwise in great shape.',
    price: 200,
    category: 'Furniture',
    location: 'San Francisco, CA',
    images: ['https://placehold.co/600x400'],
    seller: users[1],
    createdAt: '2024-05-18T16:45:00Z',
  },
  {
    id: 'listing-6',
    title: 'Laptop - 2021 Model',
    description: '13-inch laptop, great for students or professionals. Wiped and ready for a new owner. Comes with charger.',
    price: 600,
    category: 'Electronics',
    location: 'Palo Alto, CA',
    images: ['https://placehold.co/600x400', 'https://placehold.co/600x400'],
    seller: users[2],
    createdAt: '2024-05-23T08:20:00Z',
  },
    {
    id: 'listing-7',
    title: 'Camping Tent for 4 People',
    description: 'Spacious 4-person tent, used only once. Waterproof and easy to set up. All poles and stakes included.',
    price: 80,
    category: 'Sporting Goods',
    location: 'San Jose, CA',
    images: ['https://placehold.co/600x400'],
    seller: users[0],
    createdAt: '2024-05-24T18:00:00Z',
  },
  {
    id: 'listing-8',
    title: 'Vintage Film Camera',
    description: 'A classic 35mm film camera. Fully functional, a great way to get into analog photography.',
    price: 120,
    category: 'Cameras',
    location: 'Oakland, CA',
    images: ['https://placehold.co/600x400', 'https://placehold.co/600x400'],
    seller: users[1],
    createdAt: '2024-05-23T15:10:00Z',
  },
  {
    id: 'listing-9',
    title: 'Hardcover Book Collection',
    description: 'Set of 10 classic novels in hardcover. Great for decoration or reading.',
    price: 50,
    category: 'Books',
    location: 'San Francisco, CA',
    images: ['https://placehold.co/600x400'],
    seller: users[2],
    createdAt: '2024-05-22T19:30:00Z',
  },
  {
    id: 'listing-10',
    title: 'Kitchen Mixer',
    description: 'Powerful stand mixer, perfect for baking. Comes with dough hook, whisk, and paddle attachments.',
    price: 180,
    category: 'Appliances',
    location: 'Daly City, CA',
    images: ['https://placehold.co/600x400'],
    seller: users[0],
    createdAt: '2024-05-25T12:00:00Z',
  },
  {
    id: 'listing-11',
    title: 'Yoga Mat and Blocks',
    description: 'Barely used yoga mat with two foam blocks. High-quality, non-slip material.',
    price: 25,
    category: 'Sporting Goods',
    location: 'Berkeley, CA',
    images: ['https://placehold.co/600x400'],
    seller: users[1],
    createdAt: '2024-05-25T10:00:00Z',
  },
  {
    id: 'listing-12',
    title: 'Framed Art Print',
    description: 'Large framed abstract art print. Adds a pop of color to any room. 24x36 inches.',
    price: 90,
    category: 'Home Decor',
    location: 'San Francisco, CA',
    images: ['https://placehold.co/600x400', 'https://placehold.co/600x400'],
    seller: users[2],
    createdAt: '2024-05-24T11:00:00Z',
  },
];

export const conversations: Conversation[] = [
  {
    id: 'convo-1',
    listing: { id: 'listing-1', title: 'Vintage Leather Sofa', images: listings[0].images },
    participants: [users[1], users[0]],
    messages: [
      { id: 'msg-1-1', text: 'Hi, is this sofa still available?', senderId: 'user-1', timestamp: '2024-05-21T14:00:00Z' },
      { id: 'msg-1-2', text: 'Yes, it is!', senderId: 'user-0', timestamp: '2024-05-21T14:05:00Z' },
    ],
  },
  {
    id: 'convo-2',
    listing: { id: 'listing-2', title: 'Mountain Bike, Like New', images: listings[1].images },
    participants: [users[2], users[1]],
    messages: [
      { id: 'msg-2-1', text: 'Hey, I\'m interested in the bike. What\'s the frame size?', senderId: 'user-2', timestamp: '2024-05-22T10:00:00Z' },
      { id: 'msg-2-2', text: 'It\'s a medium frame, good for someone around 5\'10".', senderId: 'user-1', timestamp: '2024-05-22T10:15:00Z' },
      { id: 'msg-2-3', text: 'Perfect, can I come see it this weekend?', senderId: 'user-2', timestamp: '2024-05-22T10:20:00Z' },
    ],
  },
];

export const getListingById = (id: string) => listings.find(l => l.id === id);
export const getConversationById = (id: string) => conversations.find(c => c.id === id);

export const categories = [...new Set(listings.map(l => l.category))].sort();
